### ISSUE TITLE
Wrong parsing of register access mode

### ISSUE THREAD

**Issue by xoriath** [Rahix/atdf2svd#23]
Register access is specified by an rw attribute on the register element, not by the ocd-rw attribute.

If rw is missing, it is to be interpreted as "RW".
ocd-rw is used to indicate destructive accesses to a register, and thus lock a debugger out from doing destructive reads and writes to a register.

**Comment by Rahix** [comment]
Interesting... I guess this explains why we needed to patch the access mode so often in the generated SVD files.  Thanks for mentioning this!

I hope it's not too much to ask, but do you know of any documentation of the ATDF format?  Back when creating this tool I couldn't really find anything, so we had to go by guesswork for the most part.

**Comment by xoriath** [comment]
Not to much too ask... Let me dig a bit...

In the mean time, is there any nagging issues with the atdf format that you know of? (I see there's an issue on nested register-groups, I showed how that looks in the C side).

Is there a spec or something on how the rust access should look?

**Comment by Rahix** [comment]
> I see there's an issue on nested register-groups

I think the nested register groups are not a problem, we can't represent them directly in SVD but I think we can get around that by "flattening" them, essentially.  The bigger problem are the overlapping modes - I don't see how we can represent them in SVD or in the Rust API... Maybe just duplicating the entire peripheral for each mode?  I guess this is mostly a difficulty stemming from the hardware itself, though, not a problem with ATDF.

> Is there a spec or something on how the rust access should look?

Well, it works a lot differently from what you'd see in C.  We're transforming the SVD to Rust using [`svd2rust`](https://github.com/rust-embedded/svd2rust) which produces a big API module for each register and its fields.  This API is supposed to only allow correct register accesses by design, preventing misuse at compile time.  It is documented here: https://docs.rs/svd2rust/0.17.0/svd2rust/#peripheral-api

In practice, register accesses then look like this, for example (taken from the USART driver):

```rust
fn raw_init<CLOCK>(&mut self, baudrate: usart::Baudrate<CLOCK>) {
    self.ubrr0.write(|w| unsafe { w.bits(baudrate.ubrr) });
    self.ucsr0a.write(|w| w.u2x0().bit(baudrate.u2x));

    // Enable receiver and transmitter but leave interrupts disabled.
    self.ucsr0b.write(|w| w.txen0().set_bit().rxen0().set_bit());

    // Set frame format to 8n1 for now.  At some point, this should be made
    // configurable, similar to what is done in other HALs.
    self.ucsr0c.write(|w| {
        w.umsel0().usart_async()
         .ucsz0().chr8()
         .usbs0().stop1()
         .upm0().disabled()
    });
}

fn raw_flush(&mut self) -> nb::Result<(), Void> {
    if self.ucsr0a.read().udre0().bit_is_clear() {
        Err(nb::Error::WouldBlock)
    } else {
        Ok(())
    }
}

fn raw_write(&mut self, byte: u8) -> nb::Result<(), void::Void> {
    self.raw_flush()?;
    self.udr0.write(|w| unsafe { w.bits(byte) });
    Ok(())
}

fn raw_read(&mut self) -> nb::Result<u8, Void> {
    if self.ucsr0a.read().rxc0().bit_is_clear() {
        return Err(nb::Error::WouldBlock);
    }
    Ok(self.udr0.read().bits())
}
```

(for completeness, the actual code looks a bit more messy because it uses macros to allow instantiation for all USARTs instead of just USART0)

While you see lots of functions being called here, this is actually all optimized away.  In the end you're left with just the same single instruction writes (for `.write()`) or RMW sequences (for `.modify()`) which you'd get in C.

**Comment by xoriath** [comment]
Aha, I see... So instead of doing a custom IO layer, use the SVD one.. Obvious when the dots connect...

Both of these constructs should already be present in the Atmel/Microchip SAM devices, so in theory it should be simple enough to dig out a atdf/svd pair for an ARM part and see how that translation is done there...

**Comment by Rahix** [comment]
That's a good idea, I'll take a look.  Thanks!

**Comment by xoriath** [comment]
@Rahix : https://schemas.microchip.com/com/microchip/atdf/4.5/atdf.xsd

**Comment by Rahix** [comment]
Hmm, I cannot resolve schemas.microchip.com... Maybe that DNS name is not public?

Thanks a lot anyway for digging this up!
